spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/camunda
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop


camunda.bpm:
  admin-user:
    id: demo
    password: demo
  database:
    type: postgres
    table-prefix: camunda
    schema-update: false
    schema-name: camunda


